# Generated by Django 4.1.4 on 2023-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balaji_IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='idcards/balaji')),
            ],
        ),
        migrations.RenameModel(
            old_name='IDCard',
            new_name='Pak_IdCard',
        ),
    ]
