# Generated by Django 4.1.4 on 2023-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_balaji_idcard_rename_idcard_pak_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='balaji_idcard',
            name='mobile',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balaji_idcard',
            name='dob',
            field=models.CharField(max_length=40),
        ),
    ]
