# Generated by Django 4.1.4 on 2023-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_balaji_idcard_mobile_alter_balaji_idcard_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pak_idcard',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
