# Generated by Django 4.1.4 on 2023-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pak_idcard_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balaji_idcard',
            name='image',
            field=models.ImageField(upload_to='idcards'),
        ),
    ]
