# Generated by Django 5.0.6 on 2024-06-09 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_balaji_idcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
