# Generated by Django 5.0.6 on 2024-06-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_template_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pak_IdCard',
        ),
    ]
